spring:
  application:
    name: Liquibase-Test-Application
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:User;MODE=POSTGRESQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: kcbrewron
    password: test-password  liquibase:    enabled: true
    user: kcbrewron
    password: test-password
    change-log: db.changelog-master.yml